```{r, message=FALSE, eval=FALSE, include=FALSE}
for (yr in years) {
  print(matches_by_team %>%
          filter(year == yr) %>%
          group_by(team) %>%
          summarize(played = n(), avg_score = mean(score)) %>%
          ungroup() %>%
          ggplot(aes(played, avg_score)) +
          geom_jitter() +
          geom_smooth() +
          labs(title = str_c("Matches Played vs Average Score - ", as.character(yr))))
}
```

```{r, eval=FALSE, include=FALSE}
matches %>%
  filter(comp_level == "qm") %>%
  group_by(year, match_number) %>%
  summarize(played = n(), year = year) %>%
  ggplot() +
  geom_point(aes(match_number, played, color = as.factor(year)))
```

```{r, eval=FALSE, include=FALSE}
qm_mean_chart <- function(df) {
  df %>%
    filter(comp_level == "qm") %>%
    group_by(match_number) %>%
    summarize(mean_red = mean(red_score), mean_blue = mean(blue_score), matches = n(), event_type = event_type) %>%
    ggplot() +
    geom_point(aes(match_number, mean_blue, alpha = matches), color = "blue") +
    geom_point(aes(match_number, mean_red, alpha = matches), color = "red") +
    geom_smooth(aes(match_number, mean_blue), color = "blue") +
    geom_smooth(aes(match_number, mean_red), color = "red") +
    facet_wrap(vars(event_type))
}

qf_mean_chart <- function(df) {
  df %>%
    filter(comp_level == "qf") %>%
    group_by(match_number) %>%
    summarize(mean_red = mean(red_score), mean_blue = mean(blue_score), matches = n(), event_type = event_type) %>%
    ggplot() +
    geom_point(aes(as.factor(match_number), mean_blue, size = matches), color = "blue") +
    geom_point(aes(as.factor(match_number), mean_red, size = matches), color = "red")
}

el_mean_chart <- function(df) {
  df %>%
    filter(comp_level != "qm") %>%
    ggplot() +
    geom_violin(aes(comp_level, score)) +
    facet_wrap(vars(event_type))
}
matches %>%
  filter(year == 2018) %>%
  group_by(event_type) %>%
  summarize(matches = n())
matches %>%
  filter(year == 2018) %>%
  qm_mean_chart()

matches %>%
  filter(year == 2018) %>%
  qf_mean_chart()


for (yr in years) {
  print(scores %>%
          filter(year == yr) %>%
          ggplot() +
          geom_violin(aes(comp_level, score)) +
          facet_wrap(vars(event_type)) +
          labs(title = as.character(yr)))
}

```


```{r, message=FALSE, eval=FALSE, include=FALSE}
for (yr in years) {
  print(scores %>%
          filter(year == yr) %>%
          ggplot() +
          geom_violin(aes(week, score)) +
          labs(title = str_c("Score Distribution by Week - ", as.character(yr))))
}
```

```{r, eval=FALSE, include=FALSE}
for (yr in years) {
  print(scores %>%
          filter(year == yr) %>%
          ggplot() +
          geom_violin(aes(as.factor(event_type), score)) +
          labs(title = as.character(yr)))
}
```

```{r, eval=FALSE}
team_nums <- c(16, 33, 111, 118, 148, 254, 330, 900, 1114, 1678, 1816, 2052, 2056, 2220, 2846, 2855, 3130, 4536, 5172, 5434)
for (i in 1:length(team_nums)) {
  print(team_percentile_by_year %>%
          filter(team_num == team_nums[i]) %>%
          ggplot(aes(as.factor(year), percentile, group = 1)) +
          geom_point() +
          geom_line() +
          ylim(0, 100) +
          labs(title = str_c("Team ", as.character(team_nums[i])),
               x = "Year",
               y = "Percentile"))
}
```

```{r, message=FALSE, echo = FALSE, eval = FALSE}
for (yr in years) {
  print(team_events_per_year %>%
          left_join(team_percentile_by_year, by = c("team", "team_num", "year")) %>%
          filter(year == yr) %>%
          ggplot() +
          geom_boxplot(aes(x = as.factor(events), y = percentile)) +
          labs(x = "Number of Events Attended",
              y = "Score Percentile for Year",
              title = as.character(yr)))
}
```

```{r, message = FALSE, echo = FALSE, eval = FALSE}
for (yr in years) {
  print(team_events_per_year %>%
          filter(year == yr) %>%
          inner_join(matches_by_team, by = c("team", "team_num", "year")) %>%
          group_by(team, year, events, week) %>%
          summarize(matches = n()) %>%
          ggplot() +
          geom_boxplot(aes(x = week, y = events)) +
          labs(x = "Week",
               y = "Number of Events the Teams Attended Throughout the Year",
               title = as.character(yr)))
}
```